[project]
name = "chainlit"
version = "2.6.5-dev"
description = "Chainlit with login fix"
dependencies = []

[tool.setuptools]
packages = ["backend"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"